version: '3'
services:
    minecraft-server:
        restart: always
        environment:
            - MEMOMRY=1G
            - TYPE=SPIGOT
            - VERSION=1.15.1
            - EULA=TRUE
        volumes:
            - '/opt/container_data/spigot:/data'
        ports:
            - '25565:25565'
        container_name: mc
        image: itzg/minecraft-server
